# Generated by issue #1 — do not edit by hand.
# Edit the issue and re-run the workflow, or open a follow-up PR.

terraform {
  required_providers {
    databricks = {
      source                = "databricks/databricks"
      configuration_aliases = [databricks.account, databricks.workspace]
      version               = ">= 1.50.0"
    }
  }
}

module "team_demo_analytics" {
  source = "../../modules/uc_team_provisioning"

  providers = {
    databricks.account   = databricks.account
    databricks.workspace = databricks.workspace
  }

  team_name       = "demo-analytics"
  workspace_id    = 1234567890
  sandbox_catalog = "sandboxes"

  tags = {
    cost_center = "ENG-DEMO-001"
    team        = "demo-analytics"
    data_domain = "engineering"
  }
}
