# Generated by issue #6 — granting alice.smith@example.com the gold-readers role on finance_prod.
# To revoke, delete this file and merge.

data "databricks_user" "alice_smith" {
  user_name = "alice.smith@example.com"
}

resource "databricks_group_member" "alice_smith_gold_readers" {
  group_id  = databricks_group.gold_readers.id
  member_id = data.databricks_user.alice_smith.id
}
