# Generated by issue #8 — granting filipe.deo@databricks.com the gold-readers role on finance_prod.
# To revoke, delete this file and merge.

data "databricks_user" "filipe_deo" {
  user_name = "filipe.deo@databricks.com"
}

resource "databricks_group_member" "filipe_deo_gold_readers" {
  group_id  = databricks_group.gold_readers.id
  member_id = data.databricks_user.filipe_deo.id
}
